debezium/debezium-operator

examples/postgres/010_debezium-server-ephemeral.yml

https://issues.redhat.com/browse/DBZ-6548

DBZ-6548 using correct debezium/server image in examples

---

src/main/java/io/debezium/operator/config/ConfigMapping.java
src/test/java/io/debezium/operator/config/ConfigMappingTest.java

https://issues.redhat.com/browse/DBZ-6560

DBZ-6560 don't include null values in configuration properties

---

pom.xml
src/main/examples/postgres/001_postgresql.yml
src/main/examples/postgres/002_kafka-ephemeral.yml
src/main/examples/postgres/010_debezium-server-ephemeral.yml

https://issues.redhat.com/browse/DBZ-6549

DBZ-6549 updating examples with correct image tags on releases

---

pom.xml

https://issues.redhat.com/browse/DBZ-6994

DBZ-6994 Fixed OLM bundle versioning for stable releases

---

src/main/java/io/debezium/operator/DebeziumCsvMetadata.java

https://issues.redhat.com/browse/DBZ-7000

DBZ-7000 Fixed invalid Zulip chat URL in CSV metadata

---

pom.xml
src/main/java/io/debezium/operator/DebeziumCsvMetadata.java

https://issues.redhat.com/browse/DBZ-7003

DBZ-7003 Added missing .metadata.annotations.repository field to CSV metadata

---

src/main/java/io/debezium/operator/DebeziumServer.java

https://issues.redhat.com/browse/DBZ-7011

DBZ-7011 Added displayName and description metadata to DebeziumServer OLM metadata

---

pom.xml

https://issues.redhat.com/browse/DBZ-7048

DBZ-7048 Updated qosdk dependency and switched to qosdk platform bom

---

README.md
src/main/java/io/debezium/operator/DebeziumServerReconciler.java
src/main/java/io/debezium/operator/dependent/DeploymentDependent.java
src/main/java/io/debezium/operator/dependent/JmxServiceDependent.java
src/main/java/io/debezium/operator/dependent/conditions/JmxEnabled.java
src/main/java/io/debezium/operator/dependent/discriminators/JmxServiceDiscriminator.java
src/main/java/io/debezium/operator/model/CommonLabels.java
src/main/java/io/debezium/operator/model/JmxConfig.java
src/main/java/io/debezium/operator/model/Runtime.java
src/main/java/io/debezium/operator/util/StringUtils.java
src/test/java/io/debezium/operator/util/StringUtilTest.java

https://issues.redhat.com/browse/DBZ-7053
https://issues.redhat.com/browse/DBZ-7064

DBZ-7053 JMX access & DBZ-7064 Label consolidation

---

k8/debeziumservers.debezium.io-v1.yml
src/main/java/io/debezium/operator/dependent/DeploymentDependent.java
src/main/java/io/debezium/operator/model/JmxAuthentication.java
src/main/java/io/debezium/operator/model/JmxConfig.java

https://issues.redhat.com/browse/DBZ-7087

DBZ-7087 Ability to protect JMX with password credentials

---

examples/postgres/010_debezium-server-ephemeral.yml
k8/debeziumservers.debezium.io-v1.yml
k8/kubernetes.yml
src/main/java/io/debezium/operator/DebeziumServerReconciler.java
src/main/java/io/debezium/operator/dependent/DeploymentDependent.java
src/main/java/io/debezium/operator/dependent/ServiceAccountDependent.java
src/main/java/io/debezium/operator/dependent/conditions/CreateServiceAccount.java
src/main/java/io/debezium/operator/model/Runtime.java

https://issues.redhat.com/browse/DBZ-7111

DBZ-7111 Ability to use exiting service account to run Debezium Server pod

---

src/test/java/io/debezium/operator/config/ConfigMappingTest.java

https://issues.redhat.com/browse/DBZ-7090

DBZ-7090 Add unittests for ConfigMapping class

---

debezium-operator-api/pom.xml
debezium-operator-api/src/main/java/io/debezium/operator/api/model/DebeziumServer.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/status/DebeziumServerStatus.java

https://issues.redhat.com/browse/DBZ-6550

DBZ-6550 Sundrio builder generation of operator model classes

---

pom.xml

https://issues.redhat.com/browse/DBZ-7361

DBZ-7361 Bump QOSDK to version 6.5.1

---

pom.xml

https://issues.redhat.com/browse/DBZ-7455

DBZ-7455 Consolidated quarkus app / olm bundle / helm versions

---

debezium-operator-dist/pom.xml
debezium-operator-dist/src/main/assemblies/helm.xml
pom.xml

https://issues.redhat.com/browse/DBZ-7116

DBZ-7116 Helm chart generation and assembly

---

debezium-operator-api/src/main/java/io/debezium/operator/api/model/templates/ContainerTemplate.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/templates/Probe.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/templates/Probes.java
debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/DeploymentDependent.java
docs/reference.adoc
k8/debeziumservers.debezium.io-v1.yml
k8/kubernetes.yml

https://issues.redhat.com/browse/DBZ-7476

DBZ-7476 Making probe timings configurable

---

examples/postgres/010_debezium-server-ephemeral.yml
k8/debeziumservers.debezium.io-v1.yml
k8/kubernetes.yml
pom.xml

https://issues.redhat.com/browse/DBZ-7522

DBZ-7522 fixed qualifier resolution and upgraded QOSDK

---

k8/kubernetes.yml
pom.xml

https://issues.redhat.com/browse/DBZ-7703

DBZ-7703 Updated version of QOSDK and Quarkus

---

examples/postgres/010_debezium-server-ephemeral.yml
k8/kubernetes.yml
pom.xml

https://issues.redhat.com/browse/DBZ-7415

DBZ-7415 Disabling vcs-uri annotation generation

---

debezium-operator-api/src/main/java/io/debezium/operator/api/model/runtime/Runtime.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/runtime/metrics/JmxExporter.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/runtime/metrics/Metrics.java
debezium-operator-core/src/main/java/io/debezium/operator/core/DebeziumServerReconciler.java
debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/DeploymentDependent.java
debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/JmxExporterServiceDependent.java
debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/conditions/JmxExporterEnabled.java
debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/discriminators/JmxExporterServiceDiscriminator.java
docs/reference.adoc
k8/debeziumservers.debezium.io-v1.yml
k8/kubernetes.yml

https://issues.redhat.com/browse/DBZ-7914

DBZ-7914 Ability to enable Prometheus JMX exporter via CR

---

debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/JmxExporterServiceDependent.java

https://issues.redhat.com/browse/DBZ-7934

DBZ-7934: Fixed JMX Exporter service k8s service name

---

systemtests/src/test/java/io/debezium/operator/systemtests/resources/operator/DebeziumOperatorBundleResource.java
systemtests/src/test/resources/server/default-server.yaml

https://issues.redhat.com/browse/DBZ-7985

DBZ-7985 Fix systemtest images

---

debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/AbstractStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/FileStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/InMemoryStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/RedisStore.java

https://issues.redhat.com/browse/DBZ-8007

DBZ-8007 Fixed missing configuration prefix for offset/history store configuration

---

pom.xml

https://issues.redhat.com/browse/DBZ-7224
Follows on https://github.com/debezium/debezium/pull/5654

DBZ-7224 Switched to centralised JDK version control

---

debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/DeploymentDependent.java

Relates to  https://github.com/debezium/debezium-examples/pull/357
see also https://issues.redhat.com/browse/DBZ-8229

DBZ-8206 Changed server config volume path

---

debezium-operator-api/src/main/java/io/debezium/operator/api/config/ConfigMappable.java
debezium-operator-api/src/main/java/io/debezium/operator/api/config/ConfigMapping.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/ConfigProperties.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/DebeziumServer.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/DebeziumServerSpec.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/Format.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/FormatType.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/Predicate.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/Quarkus.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/Sink.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/Transformation.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/runtime/Runtime.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/runtime/RuntimeApi.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/Offset.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/SchemaHistory.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/Source.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/AbstractStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/CustomStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/FileStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/KafkaStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/RedisStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/RedisStoreWaitConfig.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/Store.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/offset/KafkaOffsetStore.java
debezium-operator-api/src/test/java/io/debezium/operator/api/config/ConfigMappingTest.java
debezium-operator-api/src/test/java/io/debezium/operator/api/model/runtime/RuntimeConfigTest.java

https://issues.redhat.com/browse/DBZ-8431

DBZ-8431 Ability to access primary CR in component configurations

---

debezium-operator-core/src/main/java/io/debezium/operator/core/dependent/discriminators/ApiServiceDiscriminator.java

https://issues.redhat.com/browse/DBZ-8464

DBZ-8464 Using correct label in API Service discriminator

---

debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/offset/JdbcOffsetStore.java
debezium-operator-api/src/main/java/io/debezium/operator/api/model/source/storage/schema/JdbcSchemaHistoryStore.java
debezium-operator-api/src/test/java/io/debezium/operator/api/model/runtime/JdbcOffsetConfigTest.java

closes: https://issues.redhat.com/browse/DBZ-8543

DBZ-8543 Fix JdbcOffsetStore and JdbcSchemaHistoryStore

---

systemtests/src/test/resources/redis/redis-pod.yaml

related to: https://issues.redhat.com/browse/DBZ-8564

DBZ-8564 Remove reference to dockerhub registry

---

systemtests/pom.xml
systemtests/src/test/java/io/debezium/operator/systemtests/resources/databases/MysqlResource.java
systemtests/src/test/java/io/debezium/operator/systemtests/resources/server/DebeziumServerList.java
systemtests/src/test/java/io/debezium/operator/systemtests/resources/sinks/RedisResource.java

closes: https://issues.redhat.com/browse/DBZ-8857

DBZ-8857 Remove lombok dependency

---

.github/actions/build-operator/action.yml
.github/actions/install-core/action.yml
pom.xml

https://issues.redhat.com/browse/DBZ-9246

DBZ-9246 Align jandex version to debezium parent

---

.github/actions/build-operator/action.yml

closes: https://issues.redhat.com/browse/DBZ-9429

DBZ-9429 Check pull request core branch only on pull request
